// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransGGP.Infrastructure.Data;

#nullable disable

namespace TransGGP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TransGGP.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Dolly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Dollys");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroOperador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Semirremolque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Semirremolques");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ConfiguracionId")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("DollyId")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FolioFactura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraCita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroEmbarque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroRemision")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("SemirremolqueId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCarga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConfiguracionId");

                    b.HasIndex("DollyId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("SemirremolqueId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PuedeEditarClientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditarConfiguraciones")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditarDollys")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditarOperadores")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditarSemirremolques")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditarServicios")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditarUnidades")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerClientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerConfiguraciones")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerDollys")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerOperadores")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerSemirremolques")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerServicios")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerUnidades")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Servicio", b =>
                {
                    b.HasOne("TransGGP.Domain.Models.Cliente", "Cliente")
                        .WithMany("Servicios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransGGP.Domain.Models.Configuracion", "Configuracion")
                        .WithMany()
                        .HasForeignKey("ConfiguracionId");

                    b.HasOne("TransGGP.Domain.Models.Dolly", "Dolly")
                        .WithMany()
                        .HasForeignKey("DollyId");

                    b.HasOne("TransGGP.Domain.Models.Operador", "Operador")
                        .WithMany("Servicios")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransGGP.Domain.Models.Semirremolque", "Semirremolque")
                        .WithMany()
                        .HasForeignKey("SemirremolqueId");

                    b.HasOne("TransGGP.Domain.Models.Unidad", "Unidad")
                        .WithMany("Servicios")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Configuracion");

                    b.Navigation("Dolly");

                    b.Navigation("Operador");

                    b.Navigation("Semirremolque");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Cliente", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Operador", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("TransGGP.Domain.Models.Unidad", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
